### ISSUE TITLE
Install on ubuntu

### ISSUE THREAD

**Issue by jsdizon** [LarkIT/newrelic-nfsiostat#19]
Hi @TJM, sorry for creating an issue but is there any way to install this on ubuntu? or does it tested on ubuntu? Thanks!

**Comment by TJM** [comment]
I don't think anyone has put any testing in or built any packages, but you can probably install from source. https://github.com/LarkIT/newrelic-nfsiostat#source ... I don't think there is anything too CentOS/RHEL specific?

If you need to make any changes, feel free to submit a Pull Request.

Tommy

**Comment by jsdizon** [comment]
Thanks tommy, will give update for any encountered from trying on ubuntu. Thanks!

**Comment by jsdizon** [comment]
Hi Tommy,
Sorry to disturb you, but after I installed the plugin by the source it doesn't show the server or any data on new relic dashboard, I followed the instruction on the link you gave. Please help. Have tried the source first on CentOS 6.6. Thanks man.

**Comment by jsdizon** [comment]
Hi Tommy,

nevermind this, forgot to start the daemon. but I tried it on ubuntu, the problem I encountered, the plugin was successfully installed from the source but it doesn't have the daemon script on the /etc/init.d/. So I am not able to start the plugin. Can you please advice? Thanks!

**Comment by jsdizon** [comment]
Hi @TJM,

I've encountered this error after running the "python setup.py sdist".

Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    releaseFile = open('/etc/redhat-release','r')
IOError: [Errno 2] No such file or directory: '/etc/redhat-release'

So it is built with RHEL platforms only? Thanks.

**Comment by jsdizon** [comment]
FYI, I tried this on ubuntu.

**Comment by TJM** [comment]
@jsdizon You are correct. This plugin was originally forked from https://github.com/jduncan-rva/newrhelic which is RHEL/CentOS Specific. I welcome any changes to make it more generic, or rather handle more "cases" :)

**Comment by jsdizon** [comment]
Thanks tommy. :)
